# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "scrubber"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["jasonhutchens"]
  s.date = "2013-11-19"
  s.description = "TODO: longer description of your gem"
  s.email = "jason@agworld.com.au"
  s.files = [
    ".document",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "Rakefile",
    "VERSION",
    "examples/example.rb",
    "lib/scrubber.rb",
    "lib/scrubber/list.rb",
    "lib/scrubber/presenter.rb",
    "lib/scrubber/run.rb",
    "spec/lib/scrubber/list_spec.rb",
    "spec/lib/scrubber/presenter_spec.rb",
    "spec/lib/scrubber/run_spec.rb",
    "spec/lib/scrubber_spec.rb",
    "spec/sanity/runs_without_breaking_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/jasonhutchens/scrubber"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "TODO: one-line summary of your gem"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

